on:
  push:
    branches:
      - "main"
      - "master"
    schedule:
      - cron: "0 6 * * *"

  workflow_dispatch:

jobs:
  check_dep:
    runs-on: ubuntu-latest
    name: Check python requirements file and update
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Run update_version.py
        run: |
          pip install requests
          python ./.github/workflows/update_version.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update package version
          title: Update package version
          body: The package version has been updated.
          branch: update-package-version
