on:
  push:
    branches:
      - "main"
      - "master"
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  check_dep:
    runs-on: ubuntu-latest
    name: Check python requirements file and update
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check for new package version and update
        run: |
          echo "CURRENT_VERSION=$(grep -oP 'runpod==\K[^"]+' ./builder/requirements.txt)" >> $GITHUB_ENV
          echo "NEW_VERSION=$(curl -s https://pypi.org/pypi/runpod/json | jq -r .info.version)" >> $GITHUB_ENV
          if [ -z "${{ env.action_state }}" ]; then
              echo "Failed to fetch the new version."
              exit 1
          fi
          if [ "$CURRENT_VERSION" != "${{ env.action_state }}" ]; then
              # Update requirements.txt
              sed -i "s/runpod==.*/runpod==${{ env.action_state }}/" ./builder/requirements.txt
              echo "VERSION_UPDATED=true" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.VERSION_UPDATED == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update package version
          title: Update runpod package version
          body: The package version has been updated to ${{ env.NEW_VERSION }}.
          branch: runpod-package-update
